version: '3.3'

services:

  db:
    image: postgres:14.3-alpine3.15
    hostname: '127.0.0.1'
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: advertisement